language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
 - sudo add-apt-repository ppa:mbudde/ledger -y
 - sudo apt-get update
 - sudo apt-get install ledger
 - sudo apt-get install hledger
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
