language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq hledger
# command to install dependencies
install: "sudo python setup.py install"
# command to run tests
script: nosetests
